title: Hanle Zhang
description: Personal academic website of Hanle Zhang, a PhD student in Computer Architecture.
url: https://lelecheung.github.io

owner:
  name: Hanle Zhang
  avatar: portrait.jpg
  email: zhanghanle25z@ict.ac.cn
  cv: https://lelecheung.github.io/file/CV_HanleZhang.pdf
  github: lelecheung
  linkedin: hanle-zhang-8742a22aa
  bilibili: 397683389
  zhihu: https://www.zhihu.com/people/le-le-74-47-61
  instagram: hanlezhang

links:
  - title: About Me
    url: /
  - title: CV
    url: /file/CV_HanleZhang.pdf

timezone: Asia/Shanghai
highlighter: rouge
permalink: /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
